### ISSUE TITLE
Different behaviors between pre 3.0 and 3.0+ versions

### ISSUE THREAD

**Issue by Amokrane** [JakeWharton/NineOldAndroids#20]
Hi,

First of all thanks for sharing this compatibility library with the community. I am using _NineOldAndroids_, basically to solve this [particular problem](http://stackoverflow.com/questions/10513289/android-how-to-interact-with-a-view-after-it-has-been-animated).

Before using _NineOldAndroids_, my application would crash on pre-honeycomb devices with a _ClassNotFoundException_ (for _ObjectAnimator_) and after using it, it runs fine but... I still get the same problem that I had with the animation API (the position of the animated view is still bound to its previous location). I should mention, that I don't have this problem on post-honeycomb devices.

I don't really understand why, given that your compatibility library is an extraction of the entire new API as I understand.

What do you think?

Thanks!

**Comment by JakeWharton** [comment]
This is a limitation of the platform, not the library. There is nothing you can do other than update the LayoutParams once the animation completes to get the functionality you desire.

**Comment by Amokrane** [comment]
Ok, thanks!

**Comment by jameswald** [comment]
I was having the same problem so I'm going to do what you suggest.  Thanks Jake!
