### ISSUE TITLE
animating "x" property

### ISSUE THREAD

**Issue by pzmudzinski** [JakeWharton/NineOldAndroids#24]
Can I animate "X" property using this library? All I got on pre-11 API is: 
Couldn't find setter/getter for property X with value type float
Couldn't find no-arg method for property X: java.lang.NoSuchMethodException: getX

If no, could you tell me how to read "translationX" property of a view, if this is available after Android 3.0? How is library doing that?

**Comment by Macarse** [comment]
@dzbanek: Check the `AnimatorProxy` class.

To modify those values you should do something like:

`AnimatorProxy.wrap(mView).setScaleY(1);`

**Comment by JakeWharton** [comment]
You can read (or set directly) new properties of views using the `ViewHelper` class. The sample includes demos for how to animate the other properties (like 'x').
