### ISSUE TITLE
ArgbEvaluator can't evaluate alpha value properly.

### ISSUE THREAD

**Issue by EaseTheWorld** [JakeWharton/NineOldAndroids#28]
First of all, thank you for NineOldAndroids.

I have been developing PaintAnimator.(https://github.com/EaseTheWorld/PaintAnimator)
and found that Android's ArgbEvaluator has a bug.
http://code.google.com/p/android/issues/detail?id=36158Y
(Its status is 'FutureRelease' so It will be released I guess.)

I think NineOldAndroids' user should take advantage sooner than the official release.

This is my patch in my repository.
(https://github.com/EaseTheWorld/PaintAnimator/blob/master/src/dev/easetheworld/animator/ArgbEvaluator2.java)

**Comment by JakeWharton** [comment]
Fixed on `dev`. Thanks.
