### ISSUE TITLE
onclick event on animated imageview

### ISSUE THREAD

**Issue by manjunathab** [JakeWharton/NineOldAndroids#29]
The onclick event on animated view is not working. i followed following way

animate(tv).setDuration(2000).rotationYBy(720).x(100).y(100);

```
    tv.setOnClickListener(this);
```

**Comment by SimonVT** [comment]
You're only animating where the view is drawn. When the animation is done you have to move the view to the new position.

**Comment by manjunathab** [comment]
i need to have continues animation. (INFINITE animation) in that case how i can implement the things

**Comment by SimonVT** [comment]
You need to ask this question on e.g. stackoverflow. This is not a support forum.

**Comment by manjunathab** [comment]
i didn't got answer there ... thats y i asked here...

thanks for yr valuable suggestion
