### ISSUE TITLE
Visibility setting ignored on an animated View

### ISSUE THREAD

**Issue by hrushikesh** [JakeWharton/NineOldAndroids#30]
On PreHoneycomb devices, setting the visibility of an animated view to View.GONE or View.INVISIBLE doesn't have the desired effect. (i.e., the view is still visibile on the screen.)

Steps to reproduce:
1. Start an infinite animation on a view.
2. Stop the animation after some time and immediately set the visibility of the view to GONE/Invisible
3. The view is still visibile on the screen.

Sample code follows:

```
package com.hrushikesh.uiprototypes;

import android.app.Activity;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.ImageView;

import com.nineoldandroids.animation.ObjectAnimator;
import com.nineoldandroids.animation.ValueAnimator;

public class AnimationTest extends Activity {

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_animation_test);

        final ImageView view = (ImageView) findViewById(R.id.imageView1);

        final ObjectAnimator animator = ObjectAnimator.ofFloat(view, "alpha",
                0.5f);
        animator.setRepeatCount(ValueAnimator.INFINITE);
        animator.setRepeatMode(ValueAnimator.REVERSE);
        animator.start();

        view.setOnClickListener(new OnClickListener() {

            @Override
            public void onClick(View v) {
                if (animator.isRunning()) {
                    animator.end();
                    view.setVisibility(View.INVISIBLE);
                } else {
                    view.setVisibility(View.VISIBLE);
                    animator.start();
                }
            }
        });
    }
}

```

**Comment by JakeWharton** [comment]
Correct. There is nothing I can do about this, however, as it's the only avenue for animation. I suggest you take approaches like [ActionBarSherlock does](https://github.com/JakeWharton/ActionBarSherlock/blob/4ea23b9251a799966b1b2dfcbde5a5a69cd94421/library/src/com/actionbarsherlock/internal/nineoldandroids/widget/NineFrameLayout.java#L25-35) and handle this case in the views you are animating using custom containers or simple extensions of widgets.

**Comment by wais2010** [comment]
You have to clear the view animation then you can setVisibility

animation.setAnimationListener(new Animation.AnimationListener() {

@Override
public void onAnimationStart(Animation animation) {}

@Override
public void onAnimationEnd(Animation animation) {
view.clearAnimation();
view.setVisibility(View.GONE);
}

@Override
public void onAnimationRepeat(Animation animation) {}
            });

**Comment by LukasPaczos** [comment]
@wais2010 This solved my struggle. Thanks.
