### ISSUE TITLE
Transition bug?

### ISSUE THREAD

**Issue by Andreoid82** [JakeWharton/NineOldAndroids#31]
Hi Mr Wharton,
i'm trying to do a simple transitionY animation:
I have a RelativeLayout and i move it up and down just pressing a button.
The animation works great but i think that the response of the button stay in the original position.
It seems that the animation move only the graphics and the button touch area stay in the original position and not in the "new" position.

What's wrong?

Thank you very much!
Andrea

**Comment by JakeWharton** [comment]
This is simply a fundamental limitation of animating touchable views on pre-Honeycomb. There is no workaround for the animation portion. I recommend that when your animation completes, you modify the `LayoutParams` of the view that you are animating to actually move it to its destination position.

**Comment by nobre84** [comment]
This is very unfortunate! What is sad is that its not mentioned on the project home page - at least I didn't find it. Even being aware of the limitations of Animations pre-honeycomb, it seemed these limitations were handled and abstracted away by the library! Unfortunately I'll still need to do conditional code to update view positions
The library is great, a life saver! But this one really hurt :(
