### ISSUE TITLE
Which version should I use when I use ActionBarSherlock already?

### ISSUE THREAD

**Issue by kkocel** [JakeWharton/NineOldAndroids#33]
Now I'm using separate NineOldAndroids but I've noticed that there is version of it inside ActionBarSherlock. Which implementation should I use?

**Comment by SimonVT** [comment]
Use the separate library. The one bundled in ABS is not a complete implementation (it's just the parts that's relevant to ABS), and there's no guarantee that it even works as you'd expect.
