### ISSUE TITLE
possible to 'unstick' animation?

### ISSUE THREAD

**Issue by Drenet** [JakeWharton/NineOldAndroids#37]
I'm not entirely sure if this is a bug, a limitation, or user-error, so I'm posting here and hoping for some advice. 

I'm attempting to set the layoutparams of an already-animated view in the onAnimationEnd method as suggested in many of the closed issues, but it seems that when I do this, the view itself (where its clickable) moves correctly but the animated version (where it shows up) is then offset by the same number of pixels. This is my first dive into legitimate animation, but it appears that the animated translation (x + 150) is kind of 'sticking' even after I update the layoutparams, rather than clearing itself as I was hoping. I dont see any methods or documentation for clearing it manually via code - is there a way to do that?

Also, if i take the opposite approach, and update the layout params first and then animate from -x to 0, it works correctly with the exception of a momentary blip between the layout applying and the animation starting (I'm assuming that the animator calls invalidate() on the first frame before applying transitions?). if there is a way to skip the 'fill before'-esque initial draw, that would work fine for me too.

I'm using nineoldandroids-2.4.0.jar and API 10.  Any help would be appreciated.

**Comment by JakeWharton** [comment]
In normal property animation you would call things like `view.setTranslationX(0)` in your callback. Since those methods are obviously not available on all API levels there's a helper included with the library called `ViewHelper`. Since you are translating you should be able to call `ViewHelper.setTranslationX(view, 0)` in order to reset the position.

**Comment by Drenet** [comment]
Beautiful - that works perfectly! Thank you very much for the quick response to set me straight, not to mention the library itself :).
