### ISSUE TITLE
ViewHelper.setX() on View with visibility GONE sets visibility to VISIBLE

### ISSUE THREAD

**Issue by nhaarman** [JakeWharton/NineOldAndroids#49]
When doing this:

```
myView.setVisibility(GONE);
ViewHelper.setX(newX, myView);
```

The `myView` object becomes visible again on pre-HC (tested on 2.3.3). On 4.2.2 this does not happen.

**Comment by JakeWharton** [comment]
Using the compatibility transformations requires an animation be playing on the view which requires it to be visible. There's no way to work around this fact.
