### ISSUE TITLE
More Intelligent Invalidation

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/NineOldAndroids#5]
Try to implement more intelligent invalidation so that the entire parent doesn't have to redraw itself.

**Comment by fpillet** [comment]
I second this. I was looking into some issues and was trying to figure out why you were invalidating the parent every time a change is made. This doesn't make sense in many cases, and is a performance killer if the parent happens to cover the whole screen.

I understand that this can be a hard issue as when rotations are involved, you'll need to compute a minimal invalidation rectangle using the 2d projection before and after -- the fact that Camera doesn't include utilities to do this doesn't make it easy

**Comment by JakeWharton** [comment]
Released with 2.3.0
