### ISSUE TITLE
Animate() is not applicable[...]

### ISSUE THREAD

**Issue by marshallino16** [JakeWharton/NineOldAndroids#50]
Hello,

I'm trying to use NineOldAndroids library to rewrite my animations but I can't animate my RelativeLayouts. 

Code : 
animate(otherContainer).setAlpha(Math.max(0f, Math.min(2f, 1f - 9f \* Math.abs(diffX2) / v.getWidth()/2)));

And I got the error : "The method animate() in the type View is not applicable for the arguments (RelativeLayout)" 

Any idea ?

**Comment by SimonVT** [comment]
View#animate is a framework method, you have to use ViewPropertyAnimator#animate(View).

**Comment by marshallino16** [comment]
Yeah, I figured it out few minutes ago.... dummy. 

Thank you
