### ISSUE TITLE
StackOverflowError on devices < 3.0

### ISSUE THREAD

**Issue by dcaunt** [JakeWharton/NineOldAndroids#7]
I get the same exception when running Path Animation, Toggles or ViewPropertyAnimator Demo on an Xperia Play (2.3) and Galaxy S (2.1) here.

E/AndroidRuntime( 4016): java.lang.StackOverflowError
E/AndroidRuntime( 4016):    at java.util.WeakHashMap.poll(WeakHashMap.java:569)
E/AndroidRuntime( 4016):    at java.util.WeakHashMap.get(WeakHashMap.java:473)
E/AndroidRuntime( 4016):    at com.nineoldandroids.view.animation.AnimatorProxy.wrap(AnimatorProxy.java:33)
E/AndroidRuntime( 4016):    at com.nineoldandroids.view.animation.AnimatorProxy.wrap(AnimatorProxy.java:35)
E/AndroidRuntime( 4016):    at com.nineoldandroids.view.animation.AnimatorProxy.wrap(AnimatorProxy.java:35)
E/AndroidRuntime( 4016):    at com.nineoldandroids.view.animation.AnimatorProxy.wrap(AnimatorProxy.java:35)
E/AndroidRuntime( 4016):    at com.nineoldandroids.view.animation.AnimatorProxy.wrap(AnimatorProxy.java:35)
E/AndroidRuntime( 4016):    at com.nineoldandroids.view.animation.AnimatorProxy.wrap(AnimatorProxy.java:35)
E/AndroidRuntime( 4016):    at com.nineoldandroids.view.animation.AnimatorProxy.wrap(AnimatorProxy.java:35)
E/AndroidRuntime( 4016):    at com.nineoldandroids.view.animation.AnimatorProxy.wrap(AnimatorProxy.java:35)
E/AndroidRuntime( 4016):    at com.nineoldandroids.view.animation.AnimatorProxy.wrap(AnimatorProxy.java:35)
E/AndroidRuntime( 4016):    at com.nineoldandroids.view.animation.AnimatorProxy.wrap(AnimatorProxy.java:35)
E/AndroidRuntime( 4016):    at com.nineoldandroids.view.animation.AnimatorProxy.wrap(AnimatorProxy.java:35)
E/AndroidRuntime( 4016):    at com.nineoldandroids.view.animation.AnimatorProxy.wrap(AnimatorProxy.java:35)
E/AndroidRuntime( 4016):    at com.nineoldandroids.view.animation.AnimatorProxy.wrap(AnimatorProxy.java:35)
E/AndroidRuntime( 4016):    at com.nineoldandroids.view.animation.AnimatorProxy.wrap(AnimatorProxy.java:35)
E/AndroidRuntime( 4016):    at com.nineoldandroids.view.animation.AnimatorProxy.wrap(AnimatorProxy.java:35)
E/AndroidRuntime( 4016):    at com.nineoldandroids.view.animation.AnimatorProxy.wrap(AnimatorProxy.java:35)
E/AndroidRuntime( 4016):    at com.nineoldandroids.view.animation.AnimatorProxy.wrap(AnimatorProxy.java:35)
E/AndroidRuntime( 4016):    at com.nineoldandroids.view.animation.AnimatorProxy.wrap(AnimatorProxy.java:35)
< and so on>

**Comment by JakeWharton** [comment]
Bah I'm an idiot. Fixed in `dev` branch. I'll have to see if I'm able to do a release at work or not... can't remember if I have the proper setup. Good catch.

**Comment by dcaunt** [comment]
No rush Jake, was just playing with the demos :)

**Comment by JakeWharton** [comment]
Released with 2.1.1. Updated on Market too.
