### ISSUE TITLE
Support for pause mecanism introduce in 4.4 ?

### ISSUE THREAD

**Issue by benjaminVadon** [JakeWharton/NineOldAndroids#76]
Hey,
At Android team they introduce many new functionality with 4.4 (and more with 5.0) for Animations, like the Pause/Resume mechanism for example, which is very useful when running long animations (and your app is paused..)

Do you plan to add more  4.x & 5.0 functions to your library ? and particularly the pause/resume mechanism, that I need for my personal case ? (you can tell me to add it myself, but not sure not forget something in copying it from source; you know far better your library)

**Comment by JakeWharton** [comment]
No new functionality will be added, sorry.

**Comment by benjaminVadon** [comment]
Thanks for reply, and I will do it another way using your lib because, for your information, your lib is better than official Animation for atleast one (important) point : you don't leak activity (for more read  https://code.google.com/p/android/issues/detail?id=78263)
