### ISSUE TITLE
ViewPropertyAnimator.start() (and some other methods) fails on Honeycomb

### ISSUE THREAD

**Issue by BeowulfBjornson** [JakeWharton/NineOldAndroids#9]
The cause is that such methods were added on API level 14 (4.0) so they don't exist on the original implementation in 3.1 and 3.2, hence causing the proxy to fail when such methods are called. I could try fixing it but preffered to open a bug report in order to get your opinion on the subject and what would your preffered solution be.

These methods are:
cancel()
getDuration()
getStartDelay()
setStartDelay()
start()

Looking at the code, I also noticed that a proxy for the native implementation of ViewPropertyAnimator is used for all API levels 11 and greater when said class was only added on API level 12. As I said, I can fix it and submit a pull request (and hopefully do it right, haven't worked with git before) but would like to hear your opinion on what the ideal solution would be. I didn't dig deep into the code yet but it doesn't seem possible to only proxy some methods and not others, so my suggestion would be to only use the native implementation on API level 14 and onwards.

**Comment by JakeWharton** [comment]
Good catch. Rolled an implementation myself since I had time to kill on a plane ride. Didn't get a chance to test it, though, since apparently a recent update borked adb on my laptop.

Take a look if you want. Otherwise I'll get to testing tonight to make sure it works.

**Comment by BeowulfBjornson** [comment]
It seems to be working. But only now I remembered what was the reason I should've waited a little bit more before updating my tablet for ICS :)

But if you wish, I can do a backup and install HC again and try it.

**Comment by JakeWharton** [comment]
Nope. Tested and released as v2.2.0. Thanks for the report! I would have never have found it myself haha
